#include <stdio.h>
#include <conio.h>
#include <iostream.h>

main()
{
int a,b,c,d,e,f;
cout <<" Masukan Nilai 1:";cin>>a;
cout <<" Masukan Nilai 2:";cin>>b;
cout <<" Masukan Nilai 3:";cin>>c;
d=a+b*c;
e=a+(b*c);
f=(a+b)*c;

cout <<"=========================\n";
cout <<"       Hasil Akhir       \n";
cout <<"=========================\n";
cout <<"\n Hasil Akhir            :"<<d<<endl;
cout <<"\n Hasil Akhir            :"<<e<<endl;
cout <<"\n Hasil Akhir            :"<<f<<ends;
getch();

}

